id: P010565
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:56:17.254975
source_metadata:
  id: bdr:W1KG21273
  title: ཀ་ཁའི་འཇའ་ཡིག
  author: ''
  volumes:
    ec5dd68b022445b4b92ff98d500fc94c:
      image_group_id: I1KG21315
      title: ''
      volume_number: 1
      total_pages: 296
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
